# -*- coding: utf-8 -*-
"""Code2_Varsha_Sundararaj

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1y02iY8vy7kpANLGC7u54Cn5t2ZW0LTot

'''

**Continuous Assessment 1 - Task 2**

Applied Statistics and Machine Learning

Student Name : Varsha Sundararaj

Student ID : 20065968

Question:

To build classification models (Decision Tree, Random Forest and SVM) predict whether a client subscribes to a term deposit.

'''

# **Data Preparation**

**Data Reading**
"""

# ----------------------------------------------------
# 1. DATA PREPARATION
#-----------------------------------------------------

# import libraries
from pandas import read_csv, get_dummies,DataFrame
# Loading dataset
data = read_csv('/content/bank.csv')
data.head(50)
data.info()

"""**Explanation**

- The dataset was loaded using pandas (read_csv) successfully and inspected using head() and info().
- This was done to understand the structure of the dataset, the number of records, the data types of each variable, and whether any missing values were present.
- The dataset contains 4521 records and 17 columns.
- No missing values were found, so no imputation was required.

**Data Cleaning**

*There is no missing data*

**Explanation:**
- The dataset was checked for missing values using info()
- Since there are no missing values in the dataset, no additional cleaning for null values was needed.
- However, checking for missing values is still an important preprocessing step because machine learning models require complete data.

**Data Encoding** -> one-hot encoding technique

- Categorical variables must be converted into numeric form before applying machine learning algorithms.
- Binary categorical features were converted into 0 and 1.
- Features with more than two categories were handled using one-hot encoding.
"""

#default, housing, loan, y - Binary Code (2 values)
#Changing the mentioned columns[default, housing, loan, y] into binary code
data['default'] = data['default'].map({'no':0,'yes':1})
data['housing'] = data['housing'].map({'no':1,'yes':0})
data['loan'] = data['loan'].map({'no':0,'yes':1})
data['y'] = data['y'].map({'no':1,'yes':0})
data.info()

"""**Explanation:**
- Binary categorical variables such as default, housing, loan, and y were converted into numeric values.
- This step is necessary because machine learning algorithms cannot directly process text labels.
- Converting them into binary values allows the models to use these variables during training and prediction.
- For binary variables such as default, housing, loan, and the target variable y, I used mapping to convert “yes” and “no” into 1 and 0.
"""

# one-hot encoding
# job, marital, education, contact, month, poutcome are multicoded
data=get_dummies(data,['job','marital','education','contact','month','poutcome'],dtype=int)
data.info()

"""**Explanation:**
- Categorical variables with multiple categories such as job, marital, education, contact, month, and poutcome were converted into numeric format using one-hot encoding with (get_dummies).
- One-hot encoding creates separate columns for each category and avoids introducing a false ranking between categories.
- This makes the data suitable for machine learning models.
"""

data.to_csv('bank_updated.csv')

"""**Divide data to x and y**"""

# splitting the feature (x) & target variable(y) and checking their shape dimensions
x=data.drop('y',axis=1)
y=data['y']
print(x.shape)
print(y.shape)

"""**Explanation:**
- The dataset was divided into input features (x) and the target variable (y).
- The input features are used by the models to learn patterns in the data.
- I used data.drop('y', axis=1) to create X and stored the target variable separately as y.
- The target variable represents whether the client subscribed to a term deposit.

**Data Scaling (x only)**
"""

# Applyig scaling for the feature scale
from sklearn.preprocessing import StandardScaler
x_scaled=StandardScaler().fit_transform(x) # mean=0, std=1
DataFrame(x_scaled)

"""**Explanation:**
- Feature scaling was applied using StandardScaler to normalize the independent variables.
- This ensures that all features are on a similar scale.
- This transforms the features to have a mean of zero and a standard deviation of one.
- Scaling is especially important for Support Vector Machine (SVM), because SVM is sensitive to the magnitude of feature values.
- Without scaling, variables with larger values could dominate the model.

**Data Splitting**
"""

# splitting the trainning and testing sets
from sklearn.model_selection import train_test_split
x_train, x_test, y_train, y_test = train_test_split(x_scaled, y, test_size=0.10, random_state=10)
print(x_train.shape)
print(x_test.shape)
print(y_train.shape)
print(y_test.shape)

"""**Explanation:**
- The dataset was split into training and testing sets using (train_test_split).
- 90% of the data was used for training and 10% for testing.
- The training set is used to build the models, while the testing set is used to evaluate how well the models perform on unseen data.
- This helps measure the generalization ability of each classifier.

**Data balancing (training set only)**
"""

# before imbalancing
y_train.value_counts()

# balance minority class
from imblearn.over_sampling import SMOTE
x_train,y_train = SMOTE(random_state=20).fit_resample(x_train,y_train)

# after balancing
y_train.value_counts()

"""**Explanation:**
- The training dataset was imbalanced, meaning one class had more samples than the other.
- To handle this problem, SMOTE (Synthetic Minority Oversampling Technique) was applied only to the training data.
- SMOTE generates synthetic samples for the minority class and balances the class distribution.
- This improves model learning and reduces bias toward the majority class.
- After applying SMOTE, both classes become more equally represented.

# **Decision Tree**

Modelling
"""

from sklearn.tree import DecisionTreeClassifier
DT_Classifier=DecisionTreeClassifier(criterion='entropy',max_depth=15)#building a model
DT_Classifier.fit(x_train, y_train)   #training
y_pred=DT_Classifier.predict(x_test)  #testing

"""**Explanation:**
- A Decision Tree Classifier was implemented using entropy as the splitting criterion.
- Entropy was chosen because it measures impurity and helps the model decide the best splits.
- The parameter max_depth=15 was used to limit tree complexity.
- The model was trained on the balanced training set and then used to predict the target values for the test data.

Evaluation
"""

from sklearn.metrics import accuracy_score,confusion_matrix,precision_score,recall_score,f1_score
Confusion_Matrix=confusion_matrix(y_test,y_pred)
print(Confusion_Matrix)

Accuracy=accuracy_score(y_test,y_pred)
print('the accuracy =', round(Accuracy*100,2),'%')

Precision=precision_score(y_test,y_pred)
print('the Precision =', round(Precision*100,2),'%')

Recall=recall_score(y_test,y_pred)
print('the Recall =', round(Recall*100,2),'%')

F1=f1_score(y_test,y_pred)
print('the F1 =', round(F1*100,2),'%')

"""**Explanation:**
- The Decision Tree model was evaluated using accuracy, precision, recall, F1-score, and confusion matrix.
- Accuracy measures overall correctness.
- Precision shows how many predicted positives are actually correct.
- Recall shows how many actual positives were correctly identified.
- F1-score balances precision and recall.
- These metrics provide a more complete evaluation than accuracy alone, especially for imbalanced data.

Method 2 - GridSearchCV
"""

from sklearn.model_selection import GridSearchCV
DT_Classifier1=DecisionTreeClassifier(criterion='entropy')
depths={'max_depth':[2,3,4,5,7,10,15,20,25,30]}

grid_search=GridSearchCV(estimator=DT_Classifier1,param_grid=depths,scoring='accuracy',cv=5) #building : 4 components
grid_search.fit(x_scaled,y)
best_depth = (grid_search.best_params_)
print(best_depth)
Accuracy=grid_search.best_score_
print('The Accuracy=',round(Accuracy*100,2),'%')
best_tree = grid_search.best_estimator_
print(best_tree)

"""**Explanation**
- GridSearchCV was used to tune the max_depth hyperparameter of the Decision Tree.
- The purpose of tuning max_depth is to control model complexity and reduce overfitting.
- The argument cv=5 means 5-fold cross-validation was used.
- In 5-fold cross-validation, the data is split into 5 parts. The model is trained on 4 parts and validated on 1 part, and this process is repeated 5 times.
- The average result is used to identify the best parameter value.
- This makes the model selection process more reliable and improves generalization.

## **Random Forest Classifier**

Modelling
"""

from sklearn.ensemble import RandomForestClassifier
RF_Classifier2=RandomForestClassifier() # building the model
RF_Classifier2.fit(x_train, y_train)    # training
y_pred=RF_Classifier2.predict(x_test)   # testing

"""**Explanation:**
- A Random Forest Classifier was implemented to improve performance compared to a single Decision Tree.
- Random Forest is an ensemble learning method that combines multiple decision trees.
- This helps reduce variance, improves model stability, and lowers the risk of overfitting.
- The model was trained on the balanced training dataset and tested on the unseen test dataset.

Evaluation
"""

from sklearn.metrics import accuracy_score,confusion_matrix,precision_score,recall_score,f1_score
Confusion_Matrix=confusion_matrix(y_test,y_pred)
print(Confusion_Matrix)

Accuracy=accuracy_score(y_test,y_pred)
print('the accuracy =', round(Accuracy*100,2),'%')

Precision=precision_score(y_test,y_pred)
print('the Precision =', round(Precision*100,2),'%')

Recall=recall_score(y_test,y_pred)
print('the Recall =', round(Recall*100,2),'%')

F1=f1_score(y_test,y_pred)
print('the F1 =', round(F1*100,2),'%')

"""**Explanation:**
- The Random Forest model was evaluated using confusion matrix, accuracy, precision, recall, and F1-score.
- These metrics help compare the performance of Random Forest with the other classification models.
- A higher F1-score indicates that the model performs well in balancing both precision and recall.
- Based on these results, Random Forest showed strong and stable performance.

Method 2 - GridSearchCV
"""

from sklearn.model_selection import GridSearchCV
RF_Classifier3=RandomForestClassifier(criterion='entropy')
no_trees={'n_estimators':[2,3,4,5,7,10,15,20,25,30]}

grid_search1=GridSearchCV(estimator=RF_Classifier3,param_grid=no_trees,scoring='accuracy',cv=5) #building : 4 components
grid_search1.fit(x_scaled,y)
best_no_trees = (grid_search1.best_params_)
print(best_no_trees)
Accuracy=grid_search1.best_score_
print('The Accuracy=',round(Accuracy*100,2),'%')
best_forest = grid_search1.best_estimator_
print(best_forest)

"""**Explanation:**
- GridSearchCV was used to tune the n_estimators hyperparameter of the Random Forest model.
- n_estimators controls the number of trees in the forest.
- Increasing the number of trees usually improves stability and predictive performance.
- The argument cv=5 indicates that 5-fold cross-validation was used to evaluate different values.
- This makes the parameter tuning process more robust and helps reduce overfitting.

## **SVM - Support Vector Machine Classifier**

Modelling
"""

from sklearn.svm import SVC
SV_Classifier4= SVC(kernel='sigmoid', C=100) #model building
SV_Classifier4.fit(x_train, y_train)     #training
y_pred1 = SV_Classifier4.predict(x_test) #testing

"""**Explanation:**
- A Support Vector Machine (SVM) classifier was implemented using a sigmoid kernel.
- SVM works by finding the optimal boundary that separates the target classes.
- The parameter "C" controls regularization and affects how strictly the model tries to classify the training data.
- The model was trained on the scaled and balanced training set and then tested on the test set.

Evaluation
"""

from sklearn.metrics import accuracy_score, confusion_matrix, precision_score, recall_score, f1_score
con_matrix=confusion_matrix(y_test,y_pred1)
print(con_matrix)

Accuracy = accuracy_score(y_test,y_pred1)
print('The Accuracy =', round(Accuracy*100,2),'%')

Percision = precision_score(y_test,y_pred1)
print('The Percision =', round(Percision*100,2),'%')

Recall = recall_score(y_test,y_pred1)
print('The Recall =', round(Recall*100,2),'%')

F1 = f1_score(y_test,y_pred1)
print('The F1 =', round(F1*100,2),'%')

"""**Explanation**
- The SVM model was evaluated using accuracy, precision, recall, F1-score, and confusion matrix.
- These metrics make it possible to compare SVM fairly with Decision Tree and Random Forest.
- Although SVM achieved reasonable precision, its recall was lower than the other models.
- This suggests that SVM may not capture the structure of this dataset as effectively.

Method2 - GridSearchCV
"""

from sklearn.model_selection import GridSearchCV
SV_Classifier5 = SVC()
kernel_C= {'kernel':['linear','polynomial','rbf','sigmoid'],'C':[0.01,0.1,1,10,100]}

grid_search2 = GridSearchCV(estimator=SV_Classifier5, param_grid=kernel_C, scoring = 'accuracy', cv=5)# building : 4 components
grid_search2.fit(x_scaled,y)# fitting : 4 tasks : training, testing ,evaluation and ranking

best_kernel_C = grid_search2.best_params_
print(best_kernel_C)
Accuracy = grid_search2.best_score_
print('The Accuracy=',round(Accuracy*100,2),'%')
best_svc = grid_search2.best_estimator_
best_svc

"""**Explanation:**
- GridSearchCV was used to tune the kernel and C hyperparameters of the SVM model.
- The kernel determines the type of decision boundary used by the classifier.
- The parameter C controls the balance between fitting the training data and generalizing to unseen data.
- cv=5 means 5-fold cross-validation was applied during tuning.
- This improves the reliability of the selected hyperparameters and helps avoid overfitting.

**Hyperparameter Tuning:**

To improve model performance, hyperparameter tuning was performed using GridSearchCV.

- For the Decision Tree, the maximum depth was tuned to control complexity.

- For Random Forest, the number of trees was tuned to improve stability and accuracy.

- For SVM, both the kernel type and regularization parameter C were tuned.

GridSearchCV used 5-fold cross-validation, where the dataset is divided into five parts, trained on four parts, and tested on one part. This process is repeated five times, and the average result is used to select the best parameters.

This approach improves reliability and helps reduce overfitting.

**Evaluation Metrics:**

Multiple evaluation metrics were used to assess model performance:

- Accuracy: measures overall correctness
- Precision: measures how many predicted positives are correct
- Recall: measures how many actual positives are correctly identified
- F1-score: balances precision and recall

F1-score is particularly important in classification problems where the dataset is imbalanced.

**Overfitting:**

Overfitting occurs when a model performs well on training data but poorly on unseen data.

To reduce overfitting:
- Cross-validation was used through "GridSearchCV"
- The depth of the Decision Tree was controlled
- Random Forest reduced variance by combining multiple trees
- The models were evaluated on a separate test set

These techniques improve generalization.

**Result Analysis:**

- The Decision Tree model performed well, but it may overfit if tree depth is not controlled.
- The Random Forest model provided the best overall performance and more stable predictions with strong F1 score and a good balance between precision and recall.
- The SVM model showed lower performance, especially in recall, which suggests weaker classification performance on this dataset.

Overall, Random Forest outperformed the other models.

**Depolyment Recommendation:**

Based on the results, the Random Forest model is recommended for deployment. It provides strong performance, handles complex relationships in the data, and reduces overfitting. Therefore, it is the most reliable model for predicting customer subscription.

**Final Conclusion**

- In conclusion, the dataset was prepared using clear preprocessing steps like encoding, scaling, and balancing.

- Three machine learning models were applied and improved using hyperparameter tuning and cross-validation.

- The model selection was not done only based on accuracy, because accuracy can be misleading when dataset is imbalanced.

- Instead, F1-score was taken as the main evaluation metric, as it gives balance between precision and recall.

- Precision makes sure that predicted positive cases are correct, while recall makes sure that actual positive cases are not missed.

- Among all the models, Random Forest got the best F1-score along with good precision and recall, so it is more reliable model.

So, Random Forest is recommended for real-world deployment.
"""